# Prometheus job to scrape blackbox metrics
- job_name: 'kube-api-blackbox'
# Path to metrics storage 
 metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
   - targets:
      - https://www.google.com
      - https://aws.amazon.com
      - https://www.youtube.com
 # Remapping configs
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter:9115
