apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/instance: kps
    app.kubernetes.io/name: grafana
  type: LoadBalancer
  ports:
  - name: grafana-lb
    protocol: TCP
    port: 80
    targetPort: 3000